### ISSUE TITLE
command-line tool validator throws an exception with an undocumented option

### ISSUE THREAD

**Issue by yonnycardenas** [keeps/commons-ip#109]
Dear friends, command-line tool validator throws an exception with an undocumented option '-r'
` java -jar commons-ip2-cli-2.2.0.jar validate -i /dev/shm/SIP1.zip
Exception in thread "main" java.lang.IllegalArgumentException: The option '-r' contains an illegal character : '-'
	at org.apache.commons.cli.OptionValidator.validateOption(OptionValidator.java:71)
	at org.apache.commons.cli.Option.<init>(Option.java:146)
	at org.apache.commons.cli.Option.<init>(Option.java:113)
	at org.roda_project.commons_ip2.validator.CLI.CLIValidator.<init>(CLIValidator.java:60)
	at org.roda_project.commons_ip2.validator.CLI.Main.main(Main.java:29)`

**Comment by luis100** [comment]
Possible same situation on: https://github.com/keeps/commons-ip/commit/278e3ee482af6b10666829a6a5bb9b2ff92c1c19#diff-fb10c0d0d6152f747a8ca45465d75311aab756fa0e6fccba7c4e7f737a9621adR66
