### ISSUE TITLE
Exception when creating a SIP without representations

### ISSUE THREAD

**Issue by luis100** [keeps/commons-ip#112]
```
Exception in thread "main" java.lang.NullPointerException
        at org.roda_project.commons_ip2.validator.utils.SipCreatorUtils.validateRepresentationPaths(SipCreatorUtils.java:101)
        at org.roda_project.commons_ip2.validator.CLI.CLICreator.start(CLICreator.java:173)
        at org.roda_project.commons_ip2.validator.CLI.Main.main(Main.java:36)
```

**Comment by JoaoGomes2110** [comment]
Fixed #109
