### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: org.roda_project.commons_ip2.mets_v1_12.beans.AmdSecType cannot be cast to org.roda_project.commons_ip2.mets_v1_12.beans.MdSecType

### ISSUE THREAD

**Issue by dvort1af** [keeps/commons-ip#213]
I try to validate the manually created SIP (attached) and I get the error.

Command: java -jar commons-ip2-cli-2.3.3.jar validate -i sip_0f23a6d3-7b43-4978-9fde-aa5444c368be.zip
Output: Exception in thread "main" java.lang.ClassCastException: org.roda_project.commons_ip2.mets_v1_12.beans.AmdSecType cannot be cast to org.roda_project.commons_ip2.mets_v1_12.beans.MdSecType
        at org.roda_project.commons_ip2.validator.component.structuralMapComponent.StructuralMapComponentValidator.validateCSIP91(StructuralMapComponentValidator.java:793)
        at org.roda_project.commons_ip2.validator.component.structuralMapComponent.StructuralMapComponentValidator.validate(StructuralMapComponentValidator.java:115)
        at org.roda_project.commons_ip2.validator.EARKSIPValidator.validateComponents(EARKSIPValidator.java:183)
        at org.roda_project.commons_ip2.validator.EARKSIPValidator.validateSubMets(EARKSIPValidator.java:207)
        at org.roda_project.commons_ip2.validator.EARKSIPValidator.validate(EARKSIPValidator.java:157)
        at org.roda_project.commons_ip2.validator.CLI.CLIValidator.validate(CLIValidator.java:213)
        at org.roda_project.commons_ip2.validator.CLI.CLIValidator.start(CLIValidator.java:157)
        at org.roda_project.commons_ip2.validator.CLI.Main.main(Main.java:30)
[sip_0f23a6d3-7b43-4978-9fde-aa5444c368be.zip](https://github.com/keeps/commons-ip/files/12575576/sip_0f23a6d3-7b43-4978-9fde-aa5444c368be.zip)

**Comment by dvort1af** [comment]
I tried java version "1.8.0_361". I also tried the current version commons-ip2-cli-2.4.0.jar with the same error. Validation worked correctly for other SIPs.

**Comment by luis100** [comment]
I confirm the issue, related to the validation of requisite CSIP 91 trying to force `amdsec` into 'mdsed' data type.
