### ISSUE TITLE
Class not found when running with Java 11

### ISSUE THREAD

**Issue by luis100** [keeps/commons-ip#37]
That was a very good idea as it complains that it cant find bind:
org.roda_project.commons_ip.utils.IPException: Error marshalling METS
        at org.roda_project.commons_ip2.utils.METSZipEntryInfo.prepareEntryforZipping(METSZipEntryInfo.java:87)
        at org.roda_project.commons_ip2.utils.ZIPUtils.zip(ZIPUtils.java:131)
        at org.roda_project.commons_ip2.model.impl.eark.EARKSIP.createZipFile(EARKSIP.java:175)
        at org.roda_project.commons_ip2.model.impl.eark.EARKSIP.build(EARKSIP.java:143)
        at org.roda_project.commons_ip2.model.impl.eark.EARKSIP.build(EARKSIP.java:97)
        at org.roda_project.commons_ip2.model.impl.eark.EARKSIP.build(EARKSIP.java:71)
        at com.digitalia.memoriaali.App.main(App.java:124)
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory]
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:421)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662)
        at org.roda_project.commons_ip2.utils.METSUtils.marshallMETS(METSUtils.java:67)
        at org.roda_project.commons_ip2.utils.METSZipEntryInfo.prepareEntryforZipping(METSZipEntryInfo.java:68)
        ... 6 more
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
        at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
        at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
        ... 11 more

_Originally posted by @SeismoReimaliMalm in https://github.com/keeps/roda/issues/1688#issuecomment-728868358_

**Comment by luis100** [comment]
Jaxb API classes were removed in Java 11. Workaround is required.


https://stackoverflow.com/questions/43574426/java-how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexceptio

**Comment by luis100** [comment]
The solution is to use java 8 or add following:

```xml
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.0-b170201.1204</version>
    </dependency>
    <dependency>
      <groupId>javax.activation</groupId>
      <artifactId>activation</artifactId>
      <version>1.1</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-runtime</artifactId>
      <version>2.3.0-b170127.1453</version>
    </dependency>

```
